{
    "os": "Linux-5.11.0-38-generic-x86_64-with-glibc2.10",
    "python": "3.8.8",
    "heartbeatAt": "2021-10-26T17:24:06.456906",
    "startedAt": "2021-10-26T17:24:02.248990",
    "docker": null,
    "gpu": "GeForce RTX 3060",
    "gpu_count": 1,
    "cpu_count": 6,
    "cuda": null,
    "args": [
        "-f",
        "/home/indika/.local/share/jupyter/runtime/kernel-dd5cf78c-31ba-4bff-960f-4b5f80941868.json"
    ],
    "state": "running",
    "program": "00.ipynb",
    "root": "/media/indika/Sync/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/NLP-with-Disaster-Tweets-V3",
    "host": "programmer-rd-ai",
    "username": "indika",
    "executable": "/media/indika/Sync/anaconda3/bin/python"
}
